[package]
name = "polkadot-availability-distribution"
version = "0.9.23"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
parity-scale-codec = { version = "3.1.2", features = ["std"] }
polkadot-primitives = { path = "../../../primitives" }
polkadot-erasure-coding = { path = "../../../erasure-coding" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-primitives = { path = "../../primitives" }
sp-core = { git = "https://github.com/futureverse-root/substrate", features = ["std"] , branch = "polkadot-v0.9.23" }
sp-keystore = { git = "https://github.com/futureverse-root/substrate", branch = "polkadot-v0.9.23" }
thiserror = "1.0.31"
rand = "0.8.5"
derive_more = "0.99.17"
lru = "0.7.5"
fatality = "0.0.6"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/futureverse-root/substrate", features = ["std"] , branch = "polkadot-v0.9.23" }
sp-keyring = { git = "https://github.com/futureverse-root/substrate", branch = "polkadot-v0.9.23" }
sp-tracing = { git = "https://github.com/futureverse-root/substrate", branch = "polkadot-v0.9.23" }
sc-network = { git = "https://github.com/futureverse-root/substrate", branch = "polkadot-v0.9.23" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
