[package]
name = "polkadot-node-subsystem-types"
version = "0.9.27"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Subsystem traits and message definitions"

[dependencies]
derive_more = "0.99.17"
futures = "0.3.21"
polkadot-primitives = { path = "../../primitives" }
polkadot-node-primitives = { path = "../primitives" }
polkadot-node-network-protocol = { path = "../network/protocol" }
polkadot-statement-table = { path = "../../statement-table" }
polkadot-node-jaeger = { path = "../jaeger" }
orchestra = { path = "../orchestra" }
sc-network = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
sp-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
sp-consensus-babe = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
sp-authority-discovery = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
smallvec = "1.8.0"
substrate-prometheus-endpoint = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
thiserror = "1.0.31"
async-trait = "0.1.56"
